### ISSUE TITLE
no way to handle streaming api websocket connections errors

### ISSUE THREAD

**Issue by wryk** [LaguneHQ/core#1]
With current `stream` method there is no way to know about underlying websocket connection errors and handle them when necessary.

Returning an event emitter decorating WebSocketConnection (or directly the WebSocketConnection event emitter) would allow to do that.

What do you think about something like `(stream: string, recieved: (message: {event: string, payload: any}) => void): Promise<WebSocketConnection>` instead of current `stream: string, recieved: (message: {event: string, payload: any}) => void)` ?

**Comment by neet** [comment]
I'm sorry I couldn't get it correctly, you mean something like this?

```diff
import { client as WebSocketClient } from 'websocket';

+  public stream = (stream: string, recieved: (message: {event: string, payload: any}) => void): WebSocketClient => {
-  public stream = (stream: string, recieved: (message: {event: string, payload: any}) => void) => {
  const params: any = { stream };

  if ( this.token ) {
    params.access_token = this.token;
  }

  const client = new WebSocketClient();

  client.on('connect', (connection) => {
    connection.on('message', (message) => {
      if (message.type === 'utf8' && message.utf8Data) {
        recieved(JSON.parse(message.utf8Data));
      }
    });
  });

+  client.connect(`${this.streamingUrl}${this.urlVersion}/streaming?${stringify(params)}`);

  // Returns instance of WebSocket.client
  // instead of client.connection
+  return client;
-  return client.connect(`${this.streamingUrl}${this.urlVersion}/streaming?${stringify(params)}`);
}
```

I think it looks better than now 😄  if I was wrong could you create a PR please?

**Comment by wryk** [comment]
Returning a `WebSocketClient' brings no real advantage other than knowing that a connection could not be made. In the case of a connection that was working but had a problem there is no way to react.

Returning a `WebSocketConnection` would allow you to listen to the `error` or `close` event which would allow you to notice that a working connection has just closed. The only detail to take into account is that the connection can only be obtained asynchronously, which forces to make `stream` asynchronous too.

I was thinking about something like that (not tested)
```typescript
import { client as WebSocketClient, connection as WebSocketConnection } from 'websocket';

public stream = (stream: string, recieved: (message: {event: string, payload: any}) => void): Promise<WebSocketConnection> => {
  const params: any = { stream };

  if ( this.token ) {
    params.access_token = this.token;
  }

  return new Promise((resolve, reject) => {
    const client = new WebSocketClient();

    client.on('connectFailed', (errorDescription) => {
      reject(errorDescription);
    });

    client.on('connect', (connection) => {
      connection.on('message', (message) => {
        if (message.type === 'utf8' && message.utf8Data) {
          recieved(JSON.parse(message.utf8Data));
        }
      });

      resolve(connection);
    });

    client.connect(`${this.streamingUrl}${this.urlVersion}/streaming?${stringify(params)}`);
  });
}
```

I hope I've been able to explain myself better ^^
I'm pretty busy right now, if I ever have time I'll do a PR. I made a way out to make sure my proposal was right for you before I spent time on it.

**Comment by neet** [comment]
Thanks for explaining 🙏  I finally got it
And yes, I think the error handling is completely better than now 💯 
If you're busy now I gonna implement it myself so if the next version was something wrong for you please PR to fix it
